apiRules:
  - exclude:
      uidRegex: Atomiled.Updater
      type: Namespace
  - exclude:
      uidRegex: Atomiled.Example
      type: Namespace
  - exclude:
      uidRegex: Atomiled.CreditTags
      type: Namespace

